version: "3.9"

services:
    portainer:
        image: portainer/portainer-ce:latest
        container_name: portainer
        #environment:
        #- TZ=America/Sao_Paulo
        volumes:
            - ${HOME}/Docker/Portainer/data:/data
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - "9000:9000/tcp"
        command: -H unix:///var/run/docker.sock
        deploy:
            resources:
                limits:
                    # Limits the CPU usage by the container to 0.5 cores.
                    cpus: '0.5'
                    # Limits the memory usage by the container to 2GB.
                    memory: 2G
        healthcheck:
            # Checks the health of the container using curl to access port 3000.
            test: ["CMD", "curl", "-f", "http://127.0.0.1:9000"]
            # The interval between each health check.
            interval: 30s
            # The maximum amount of time a health check can take before it is considered a failure.
            timeout: 10s
            # The number of consecutive health check failures required for the container to be considered unhealthy.
            retries: 6
        # The restart policy of the container. "always" means the container will be restarted regardless of the exit status.
        restart: unless-stopped
        networks:
            # The Docker network to which the container will be connected.
            - portainer-net
            
networks:
    # Defines the network to be created.
    portainer-net:
        # The name to be assigned to the network.
        name: portainer-net
